### ISSUE TITLE
email adress as key id

### ISSUE THREAD

**Issue by jcnoir** [BenoitZugmeyer/pass-web#3]
Thanks for this nice tool ! 
I do not know if it is a bad practice but I use an email adress as key id.
This works with pass, qtpass, gopass but not with pass-web. I get this error : 
```
Error: Invalid key id value XXX@YYY.ZZZ
```

May you handle email adress as key ID ?

Thanks.

**Comment by BenoitZugmeyer** [comment]
Thank you for your interest. You are not the first to tell me about this issue! I will do something, but I haven't much time right now.

**Comment by BenoitZugmeyer** [comment]
Well it was simpler than I thought. Could you try it to see if it works for you? I'll make a release soon.

**Comment by jcnoir** [comment]
Thanks your work !
I am not sure I tested it correctly : I just replaced /usr/lib/node_modules/pass-web/server/Keys.js with your new version.
I get this error : Error: Key with email XXX@YYY.ZZZ not found

I'm reallly no js expert so I may be wrong but it looks like this._keys.values() is empty in my case.

**Comment by BenoitZugmeyer** [comment]
I just published a new version on NPM and AUR. If @this._keys.values()@ is empty, then it means you didn't specify any secret key in the command line. The new version will now raise an error if there is no secret key provided, and print which email is handled by each provided key. Please let me know if you still have the issue.
