### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by chmduquesne** [BenoitZugmeyer/pass-web#30]
Hi there,

I wanted to setup a pass-web instance for emergency access. Are you still maintaining it?

Cheers,
Christophe-Marie

**Comment by BenoitZugmeyer** [comment]
I still use it daily, and I will fix bugs posted here, but the feature set is enough for my use case, so I probably won't add much features in the short term. I'd like to rework the backend (switch to a Rust backend, interfacing with gpg directly if possible) and the frontend (make it a bit more UX friendly and mobile friendly), but I'm not sure when it will happen.

**Comment by chmduquesne** [comment]
Awesome, thank you!
