### ISSUE TITLE
Security: Password are send to early

### ISSUE THREAD

**Issue by kochd** [BenoitZugmeyer/pass-web#5]
The '/get' post is send when you select the entry from the list.
The password should be send to the only when it actually asks for it by clicking on the copy button.

**Comment by BenoitZugmeyer** [comment]
The `get` request is used to get the whole file, not just the password. I want to display the file content as soon as the user clicks on it.

**Comment by kochd** [comment]
You may want to rethink that. Navigating through the UI should not cause passwords to be be send over the network when there is absolute no need for it.
