### ISSUE TITLE
Parsing of .gpg-id fails when there is more than one key

### ISSUE THREAD

**Issue by kochd** [BenoitZugmeyer/pass-web#6]
If you use pass in a team with more than just one key pass-web fails to read the .gpg-id file.
Keys are separated by \n but the whole file is red as one key. 
If the key is parsed as one string of `KEY1 KEY2 KEY3 ...` you'll hit this throw:
https://github.com/BenoitZugmeyer/pass-web/blob/0e90cc99d3f90fe753f954987e15d4540c5ce46d/server/Keys.js#L22

**Comment by BenoitZugmeyer** [comment]
Thank you for your feedback. I did try to import a PGP key file containing multiple keys, but `kbpgp` (the lib I use to handle those keys) does not allow to import such a file. How did you manage to import such a file?

Anyway, `openpgp.js` seems to allow reading multiple keys from a single file, so I may need to change the library.

**Comment by kochd** [comment]
Pass creates the file the.
Form pass manpage:
<pre>
Initialize new password storage and use gpg-id for encryption. Multiple gpg-ids may be specified, in order to encrypt each password with multiple ids.
</pre>

You just do `pass init finterprint1 fingerprint2 ...`

**Comment by kochd** [comment]
No there are multiple keys in it while pass-web is started with one of them.

**Comment by BenoitZugmeyer** [comment]
Oh I see, I'll make something about this.

**Comment by BenoitZugmeyer** [comment]
Can you try the master version to see if it fits your needs?

**Comment by kochd** [comment]
Sure. How can i start the master after is cloned it ?

**Comment by BenoitZugmeyer** [comment]
Install dependencies with `yarn` or `npm i`, then run `node server secret-key.key`

**Comment by kochd** [comment]
Yes good job. i can confirm that https://github.com/BenoitZugmeyer/pass-web/commit/e8f97ad9bba5233045742185c57edf3ed80b0f53 did the trick

**Comment by BenoitZugmeyer** [comment]
Great. I'll publish it soon.
